### ISSUE TITLE
make it work with pnpm 9.1.2

### ISSUE THREAD

**Issue by Skieransa** [natgo/wt-app#9]

**Comment by Skieransa** [comment]
> wt-app@1.1.5 build
> tsc ; vite build

error TS6231: Could not resolve the path ';' with the extensions: '.ts', '.tsx',
 '.d.ts', '.cts', '.d.cts', '.mts', '.d.mts'.
  The file is in the program because:
    Root file specified for compilation

error TS6231: Could not resolve the path 'build' with the extensions: '.ts', '.t
sx', '.d.ts', '.cts', '.d.cts', '.mts', '.d.mts'.
  The file is in the program because:
    Root file specified for compilation

error TS6231: Could not resolve the path 'vite' with the extensions: '.ts', '.ts
x', '.d.ts', '.cts', '.d.cts', '.mts', '.d.mts'.
  The file is in the program because:
    Root file specified for compilation


Found 3 errors.

**Comment by Skieransa** [comment]
thsi happened while i tried to build it
